### ISSUE TITLE
Add card functionality breaks the set

### ISSUE THREAD

**Issue by KylePlummerBSCS** [revature-quizzard/quizzard-ui#28]
adding a card to a set with Sean's functionality may break the set? more testing required

We didn't really finish up this functionality this weekend, probably just needs a once over to fix it up with new data structures and states.

**Comment by GiancarloTomasello** [comment]
Fixed on freshBranch/Everett

**Comment by GiancarloTomasello** [comment]
Merged into pre_dev_merge_party
