### ISSUE TITLE
Start quiz infinite loop

### ISSUE THREAD

**Issue by KylePlummerBSCS** [revature-quizzard/quizzard-ui#29]
bug: starting a quiz gets frozen in a loop sometimes. Not sure why.

Does happen when there aren't enough cards in a set to fill out random answers. We added an alert when there are less than 4 questions. Still occurs on some sets.

**Comment by GiancarloTomasello** [comment]
Fixed on freshBranch/Everett

**Comment by GiancarloTomasello** [comment]
Merged into pre_dev_merge_party
